name: Dogfood

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
  discussion:
    types:
      - created

jobs:
  post-comment:
    name: Post Comment
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Post Comment
        uses: ./
        with:
          regex: "^$"  # any
          message: |
            Thanks for posting #{{ number }}!
